Update `Invoke-PolicyToBicep.ps1` Scripts to Handle `-`'s,` `'s (spaces) & `'` apostrophes + Fix #254
Azure/ALZ-Bicep pull request #288
Opened 2022-07-15 15:18 UTC by jtracey93

# Overview/Summary

Update `Invoke-PolicyToBicep.ps1` Scripts to Handle `-`'s,` `'s (spaces) & `'` apostrophes + Fix #254 

## This PR fixes/adds/changes/removes

1. Update `Invoke-PolicyToBicep.ps1` Scripts to Handle `-`'s,` `'s (spaces) & `'` apostrophes
2. Fix #254 

### Breaking Changes

None.

## Testing Evidence

Local testing with ISD colleague has proved successful

![image](https://user-images.githubusercontent.com/41163455/179253598-96840df2-e837-40d4-a851-c38a5cc5da0a.png)

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [x] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [x] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [x] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

2022-07-15 18:19 UTC, SeSeicht commented
additional Task woulb be: escape `'` in names

2022-07-15 18:22 UTC, jtracey93 commented
> additional Task woulb be: escape `'` in names

Hey @SeSeicht could you provide some more explanation or screenshots of what you mean here as I can't work it out 👍

2022-07-15 19:03 UTC, SeSeicht commented
> > additional Task woulb be: escape `'` in names
> 
> Hey @SeSeicht could you provide some more explanation or screenshots of what you mean here as I can't work it out 👍

This for example
![image](https://user-images.githubusercontent.com/48480298/179293608-965b3edf-e84f-4e2a-912f-e68e5a0c6dd9.png)

2022-07-18 19:11 UTC, jtracey93 commented
/azp run validateazcloud

2022-07-19 07:08 UTC, jfaurskov commented on .github/scripts/Invoke-PolicyToBicep-China.ps1
> +DESCRIPTION: This PowerShell script outputs the Name & Path to a Bicep strucutred .txt file named '_mc_policyDefinitionsBicepInput.txt' (defintionsTxtFileName) and '_mc_policySetDefinitionsBicepInput
```suggestion
DESCRIPTION: This PowerShell script outputs the Name & Path to a Bicep structured .txt file named '_mc_policyDefinitionsBicepInput.txt' (defintionsTxtFileName) and '_mc_policySetDefinitionsBicepInput.txt' (defintionsSetTxtFileName) respectively. It also creates a parameters file for each of the policy set definitions. It also outputs the number of policy and policy set definition files to the console for easier reviewing as part of the PR process.
```

2022-07-19 07:21 UTC, jfaurskov requested changes
Other than the initial lines at the top of the scripts I have not comments

2022-07-19 08:03 UTC, merged