16989: Add bicep sample code
Azure/ALZ-Bicep pull request #355
Opened 2022-10-25 00:24 UTC by khushal08

# Overview/Summary

Sample bicep code to run different modules. 

## This PR fixes/adds/changes/removes

1. Provides an example using bicep to run a particular module. 

### Breaking Changes

1. None

## Testing Evidence

1. Tested locally by deploying the code. 
2. Tested PSRule to make sure that the pre-deployment checks pass. 

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [ ] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [ ] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

2022-10-26 02:45 UTC, khushal08 commented
@jtracey93 Can you please review? thanks

2022-10-26 06:59 UTC, jtracey93 requested changes
Hey @khushal08,

Looks like some issues we either need to fix in this PR or create separate issues for to then fix post merging this PR: https://github.com/Azure/ALZ-Bicep/actions/runs/3317756169

Let me know which way you want to go as I this is part of the feature work you have assigned.

Cheers

Jack

2022-11-02 21:55 UTC, jtracey93 commented
still active

2022-11-10 06:34 UTC, jtracey93 commented
Still active

2022-11-11 15:27 UTC, jtracey93 requested changes

2022-11-11 15:27 UTC, jtracey93 commented on .ps-rule/DiagLogForAutomation.Rule.yaml
> +# Synopsis: Ignore automation account audit diagnostic logs are enabled.
```suggestion
# Synopsis: Ignore automation account audit diagnostic logs are enabled as these are covered by DINE policies in ALZ
```

2022-11-13 23:02 UTC, khushal08 commented on .ps-rule/ManagedIdentityForAutomation.Rule.yaml
> +# Synopsis: Ignore Managed Identity is used for authentication.
I think that's a good point. We need to log a new feature request. Let me open one.

2022-11-13 23:17 UTC, khushal08 commented on .ps-rule/ManagedIdentityForAutomation.Rule.yaml
> +# Synopsis: Ignore Managed Identity is used for authentication.
Created a user story: https://dev.azure.com/CSUSolEng/Azure%20Landing%20Zones/_workitems/edit/25134
My thoughts are for now let's suppress the rule. As part of the fix for the above story, managed identity should be implemented, and suppression rule removed.

2022-11-14 11:28 UTC, jtracey93 commented
/azp run validateazcloud

2022-11-14 11:55 UTC, jtracey93 approved these changes
LGTM

2022-11-14 11:55 UTC, merged