Change deployment scope for MG Diagnostics #338
Azure/ALZ-Bicep pull request #372
Opened 2022-11-02 16:53 UTC by lachaves

# Overview/Summary

This PR changes the scope of the orchestration module mgDiagSettingsAll from tenant to mg level. 

## This PR fixes Issue #338 

### Breaking Changes

None

## Testing Evidence

The validation available here https://learn.microsoft.com/en-us/rest/api/monitor/management-group-diagnostic-settings/get?tabs=HTTP&tryIt=true&source=docs#code-try-0 was used to test. 

## As part of this Pull Request I have

- [X] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [X] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [ X] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ X] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [X] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [X ] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [X] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [X] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)
## As part of this Pull Request I have

- [X] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [X] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [ X] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ X] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [X] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [X ] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [X] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [X] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

2022-11-02 21:38 UTC, jtracey93 requested changes
Thanks @lachaves for your work here. A couple of small suggestions plus the below:

Make updates to the tests here:

1. https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml#L108
2. https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml#L197
3. https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml#L88

Thanks and let me know when good to review again 👍

2022-11-02 21:38 UTC, jtracey93 commented on infra-as-code/bicep/orchestration/mgDiagSettingsAll/mgDiagSettingsAll.bicep
> +@description('Dictionary Object to allow additional or different child Management Groups of the Landing Zones Management Group .')
```suggestion
@description('Dictionary Object to allow additional or different child Management Groups of the Landing Zones Management Group.')
```

2022-11-02 21:38 UTC, jtracey93 commented on infra-as-code/bicep/orchestration/mgDiagSettingsAll/mgDiagSettingsAll.bicep
>  }
Change this module out to use the management group scoped level version here https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/CRML/customerUsageAttribution/cuaIdManagementGroup.bicep

2022-11-03 14:43 UTC, lachaves commented
@jtracey93, Thanks for your review, suggestions and updates completed. Please validate and let me know if anything still missing.

2022-11-03 15:06 UTC, jtracey93 commented
/azp run validateazcloud

2022-11-03 15:28 UTC, jtracey93 commented
/azp run e2e

2022-11-03 17:00 UTC, jtracey93 approved these changes
LGTM

2022-11-03 17:00 UTC, merged

2022-11-08 14:58 UTC, jtracey93 commented on infra-as-code/bicep/orchestration/mgDiagSettingsAll/README.md
> +parLandingZoneMgChildren: {
@lachaves to comment

2022-11-22 21:04 UTC, lachaves commented on infra-as-code/bicep/orchestration/mgDiagSettingsAll/README.md
> +parLandingZoneMgChildren: {
I have changed the description in the parameters table and also the bicep example for the parameter to show as an array type.  Sending a PR with updates.