26016 - Feature - Child Landing Zone Management Groups Flexibility
Azure/ALZ-Bicep pull request #446
Opened 2023-02-08 14:38 UTC by JamJarchitect

# Overview/Summary

[AB#26268](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/26268)

Update MGDiagAll orchestration and introduction of a parameter to Management Group module that allows the deployer to `true` or `false` whether management groups beneath Platform are wanted in accordance with Trey Research architecture:

https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/treyresearch/README.md

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. Adds an additional parameter `parPlatformMgAlzDefaultsEnable` to the Management Group module. Values are either `true` or `false` whether child management groups are wanted under Platform management group, with `true` being default
2. Updated `mgDiagsAll.bicep` module to include Platform MG and any custom child MGs under there

### Breaking Changes

1. N/A

## Testing Evidence

![image](https://user-images.githubusercontent.com/53943045/217558745-8e3f498b-e061-462c-9c41-fd22d8faa2f3.png)

## As part of this Pull Request I have

- [X] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [X] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [X] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [X] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [X] Performed testing and provided evidence.
- [X] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [X] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [X] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

2023-02-09 11:57 UTC, jtracey93 requested changes
Great start here @JamJarchitect. However, I think this isn't quite complete yet.

You've nailed the flexibility of enabling/disabling platform children that re defaults (management, connectivity, identity) but you have enabled customers to be able to set their own custom management groups beneath the platform MG, like we say is possible in the tailoring guidance (aka.ms/alz/tailoring)

- [x] Add the ability to create custom MGs beneath Platform MG, like we do on the LZ MG here (https://github.com/JamJarchitect/ALZ-Bicep/blob/26268submggroups/infra-as-code/bicep/modules/managementGroups/managementGroups.bicep#L27-L28)
    - You'll also need the lovely `var` here: https://github.com/JamJarchitect/ALZ-Bicep/blob/26268submggroups/infra-as-code/bicep/modules/managementGroups/managementGroups.bicep#L84 
- [ ] Add the same support into the [`mgDiagSettingsAll.bicep`](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/orchestration/mgDiagSettingsAll/mgDiagSettingsAll.bicep) module

2023-02-09 14:19 UTC, JamJarchitect commented
> Great start here @JamJarchitect. However, I think this isn't quite complete yet.
> 
> You've nailed the flexibility of enabling/disabling platform children that re defaults (management, connectivity, identity) but you have enabled customers to be able to set their own custom management groups beneath the platform MG, like we say is possible in the tailoring guidance (aka.ms/alz/tailoring)
> 
> * [x]  Add the ability to create custom MGs beneath Platform MG, like we do on the LZ MG here (https://github.com/JamJarchitect/ALZ-Bicep/blob/26268submggroups/infra-as-code/bicep/modules/managementGroups/managementGroups.bicep#L27-L28)
>   
>   * You'll also need the lovely `var` here: https://github.com/JamJarchitect/ALZ-Bicep/blob/26268submggroups/infra-as-code/bicep/modules/managementGroups/managementGroups.bicep#L84
> * [x]  Add the same support into the [`mgDiagSettingsAll.bicep`](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/orchestration/mgDiagSettingsAll/mgDiagSettingsAll.bicep) module

Amendments done per your request @jtracey93 

- `do not merge` label removed
- Ready for review

2023-02-10 09:21 UTC, jtracey93 commented
@JamJarchitect really sorry, but can you also add the capability for platform flexibility to this module as well: https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/orchestration/subPlacementAll as part of this PR.

Thanks 👊👊

2023-02-14 15:38 UTC, JamJarchitect commented
Tested all modules except for subplacementall - will require additional info on that test.

Results for the MG Deployments:
![image](https://user-images.githubusercontent.com/53943045/218784837-2d8ab105-82f4-4e42-bcd0-ed377f7c29f9.png)

Parameter defaults to normal children MGs of Platform (Identity, Management, Connectivity) with the ability to `false` that. Also the ability to deploy other child MGs under Platform and `true` or `false` the normal `platform` defaults.

MGDiagsAll orchestration deploys successfully including children MGs (custom and default).

Working on SubPlacementAll test and then will remove `do not merge` label.

2023-03-02 12:49 UTC, JamJarchitect commented
**UPDATES:**
- `main` merged into my fork and also this branch
- conflicts have been worked through for suffixes
- tested functionality of `ManagementGroup' module, `subplacementall` orchestration and `mgdiagsall` orchestration on custom platform children

![image](https://user-images.githubusercontent.com/53943045/222433239-7c2796a1-76bb-41a2-ac41-6840feb2f313.png)

Checking the READMEs provide key information for new feature and will remove `do not merge` label ready for review

2023-03-03 10:28 UTC, JamJarchitect commented
/azp run validateazcloud

2023-03-09 10:08 UTC, baartch commented
@JamJarchitect Thank you very much for your efforts in providing this flexibility! 👏

I just wanted to mention that if it's not already intended to be created, this flexibility would also be needed in _Deployment Flow_ Step 8:
https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/assignments/alzDefaults

2023-03-09 13:33 UTC, jtracey93 commented
> @JamJarchitect Thank you very much for your efforts in providing this flexibility! 👏
> 
> I just wanted to mention that if it's not already intended to be created, this flexibility would also be needed in _Deployment Flow_ Step 8: [`main`/infra-as-code/bicep/modules/policy/assignments/alzDefaults](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/assignments/alzDefaults?rgh-link-date=2023-03-09T10%3A08%3A43Z)

Hey @baartch, glad you like this new feature, we will get it reviewed and merged soon.

We actually dont add the flexbility to the `alzDefaultPolicyAssignments` module as its more of a "hardcoded" bicep file that aligns to the default ALZ hierarchy, so no need for flexibility.

If you wanted to make new policy assignments to the newly created management groups via the flexibility input features, you should follow the guidance here: https://github.com/Azure/ALZ-Bicep/wiki/AssigningPolicies

Hope that helps and makes sense

Thanks

Jack

2023-03-14 11:53 UTC, JamJarchitect commented
/azp run validateazcloud

2023-03-17 14:38 UTC, stalejohnsen commented
Great addition! Any thoughts on adding flexibility to create MGs below level 3 as well? For example there could be situations where you want to further split corp in isolated and connected sub-archetypes with different guard rails but still inherit the common corp guard rails. Like this module: https://github.com/tyconsulting/BlogPosts/tree/master/Azure-Bicep/management.group

2023-03-17 15:36 UTC, jtracey93 commented
> Great addition! Any thoughts on adding flexibility to create MGs below level 3 as well? For example there could be situations where you want to further split corp in isolated and connected sub-archetypes with different guard rails but still inherit the common corp guard rails. Like this module: [tyconsulting/BlogPosts@`master`/Azure-Bicep/management.group](https://github.com/tyconsulting/BlogPosts/tree/master/Azure-Bicep/management.group?rgh-link-date=2023-03-17T14%3A38%3A24Z)

Afraid not @stalejohnsen as this goes against our tailoring guidance. Go wide, not deep is our guidance. https://aka.ms/alz/tailoring

2023-03-17 15:59 UTC, stalejohnsen commented
> > Great addition! Any thoughts on adding flexibility to create MGs below level 3 as well? For example there could be situations where you want to further split corp in isolated and connected sub-archetypes with different guard rails but still inherit the common corp guard rails. Like this module: [tyconsulting/BlogPosts@`master`/Azure-Bicep/management.group](https://github.com/tyconsulting/BlogPosts/tree/master/Azure-Bicep/management.group?rgh-link-date=2023-03-17T14%3A38%3A24Z)
> 
> Afraid not @stalejohnsen as this goes against our tailoring guidance. Go wide, not deep is our guidance. https://aka.ms/alz/tailoring

Not sure if I follow you there @jtracey93. I would argue that my suggestion of flexibility on the level/layer below corp/online is supported by the following statements in tailoring guide:

* Always try to build on the existing archetypes and hierarchy to meet new requirements. 
If I have a sub-archetype of corp, meaning - I want to differentiate my corp application with slightly different guardrails but still I want to inherit the common corp guard rails. Example: isolated corp applications with no public ips and connected corp applications (like waf mission-critical architecture). If I create a new management group on the same layer/level as corp and online - I don't have the inheritance anymore and instead I'm starting on scratch with defining the guard rail for new archetype, not a related archetype.  

* Avoid going beyond a hierarchy depth of four layers to avoid complexity and unnecessary exclusions.
My suggestion does not go beyond four layers.

2023-03-17 16:04 UTC, jtracey93 commented
> 

You left out the important part of the last points sentence "Expand archetypes horizontally instead of vertically in the hierarchy." 

Today we have not seen a requirement for this and do no plan to enable this feature, please feel to raise a feature request for this on the repo, with a diagram, and some justification for review 👍👍

2023-03-17 17:59 UTC, stalejohnsen commented
> > 
> 
> You left out the important part of the last points sentence "Expand archetypes horizontally instead of vertically in the hierarchy."
> 
> Today we have not seen a requirement for this and do no plan to enable this feature, please feel to raise a feature request for this on the repo, with a diagram, and some justification for review 👍👍
 
Will add this as a new feature request, thanks

2023-03-22 17:17 UTC, jtracey93 requested changes
Great work here @JamJarchitect i think we are just missing the MG suffix work that @mbrat2005 added in #462 in this PR.

I think i have added suggestion for everywhere they are needed, please review, accept and commit them if so 👍

2023-03-22 17:17 UTC, jtracey93 commented on infra-as-code/bicep/modules/managementGroups/managementGroups.bicep
> +  name: '${parTopLevelManagementGroupPrefix}-platform-${mg.key}'
```suggestion
  name: '${parTopLevelManagementGroupPrefix}-platform-${mg.key}${parTopLevelManagementGroupSuffix}'
```

Think we are missing the suffix additions

2023-03-22 17:17 UTC, jtracey93 commented on infra-as-code/bicep/modules/managementGroups/managementGroups.bicep
> +output outPlatformChildrenManagementGroupIds array = [for mg in items(varLandingZoneMgChildrenUnioned): '/providers/Microsoft.Management/managementGroups/${parTopLevelManagementGroupPrefix}-platform-
```suggestion
output outPlatformChildrenManagementGroupIds array = [for mg in items(varLandingZoneMgChildrenUnioned): '/providers/Microsoft.Management/managementGroups/${parTopLevelManagementGroupPrefix}-platform-${mg.key}${parTopLevelManagementGroupSuffix}']
```

2023-03-22 17:17 UTC, jtracey93 commented on infra-as-code/bicep/orchestration/mgDiagSettingsAll/mgDiagSettingsAll.bicep
> +  mgId: '${parTopLevelManagementGroupPrefix}-platform-${customMg}'
```suggestion
  mgId: '${parTopLevelManagementGroupPrefix}-platform-${customMg}${parTopLevelManagementGroupSuffix}'
```

2023-03-22 17:17 UTC, jtracey93 commented on infra-as-code/bicep/orchestration/mgDiagSettingsAll/parameters/mgDiagSettingsAll.parameters.all.json
> +      "value": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/logging-rg/providers/microsoft.operationalinsights/workspaces/alz-log-analytics"
why has this changed?

2023-03-22 17:17 UTC, jtracey93 commented on infra-as-code/bicep/orchestration/subPlacementAll/subPlacementAll.bicep
> +  scope: managementGroup('${parTopLevelManagementGroupPrefix}-platform-${mg.key}')
```suggestion
  scope: managementGroup('${parTopLevelManagementGroupPrefix}-platform-${mg.key}${parTopLevelManagementGroupSuffix}')
```

2023-03-22 17:17 UTC, jtracey93 commented on infra-as-code/bicep/orchestration/subPlacementAll/subPlacementAll.bicep
> +    parTargetManagementGroupId: '${parTopLevelManagementGroupPrefix}-platform-${mg.key}'
```suggestion
    parTargetManagementGroupId: '${parTopLevelManagementGroupPrefix}-platform-${mg.key}${parTopLevelManagementGroupSuffix}'
```

2023-03-29 18:11 UTC, jtracey93 commented
stil active

2023-04-05 15:05 UTC, JamJarchitect commented on infra-as-code/bicep/orchestration/mgDiagSettingsAll/parameters/mgDiagSettingsAll.parameters.all.json
> +      "value": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/logging-rg/providers/microsoft.operationalinsights/workspaces/alz-log-analytics"
changed this back

2023-04-06 08:40 UTC, JamJarchitect commented
/azp run validateazcloud

2023-04-06 08:45 UTC, JamJarchitect commented
/azp run validateazcloud

2023-04-13 11:46 UTC, JamJarchitect commented
/azp run validateazcloud

2023-04-13 13:10 UTC, JamJarchitect commented
/azp run validateazcloud

2023-04-18 12:02 UTC, JamJarchitect commented
/azp run validateazcloud

2023-04-18 13:12 UTC, JamJarchitect commented
/azp run validateazcloud

2023-04-18 13:43 UTC, jtracey93 commented
/azp run validateazcloud

2023-04-18 14:02 UTC, closed without merging