26808 - Feature - Add support to allow Private DNS Zone VNet Linking for Spoke VNets
Azure/ALZ-Bicep pull request #476
Opened 2023-03-13 15:55 UTC by JamJarchitect

# Overview/Summary

Adding support to allow Private DNS Zone VNet Linking for Spoke VNets through HubPeeredSpoke orchestration module and a new Private Dns Zone Linking module.

## This PR fixes/adds/changes/removes

1. Added feature to HubPeeredSpoke orchestration module to allow Private DNS Zone Linking to Spoke VNets.
2. Added new module for Private DNS Zone Linking.

### Breaking Changes

1. N/A

## Testing Evidence

Replace this with any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [X] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [X] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [X] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [X] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [X] Performed testing and provided evidence.
- [X] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [X] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [X] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

2023-03-14 14:31 UTC, JamJarchitect commented
<img width="669" alt="image" src="https://user-images.githubusercontent.com/53943045/225033810-aa708115-2c43-4ad0-8615-8f57810eef46.png">

New module working - orchestration module test to be done

2023-04-19 12:45 UTC, JamJarchitect commented
/azp run validateazcloud

2023-04-21 07:54 UTC, JamJarchitect commented
/azp run e2e

2023-04-21 14:45 UTC, jtracey93 requested changes
Looking good, couple of small changes please @JamJarchitect

2023-04-21 14:45 UTC, jtracey93 commented on infra-as-code/bicep/orchestration/hubPeeredSpoke/bicepconfig.json
> -          "level": "error"
Can we put these back?

2023-04-21 14:45 UTC, jtracey93 commented on infra-as-code/bicep/modules/privateDnsZoneLinks/samples/generateddocs/baseline.sample.bicep.md
This file shouldnt exist right?

2023-04-21 15:57 UTC, JamJarchitect commented on infra-as-code/bicep/modules/privateDnsZoneLinks/samples/generateddocs/baseline.sample.bicep.md
We have a samples folder for most modules with a generateddocs folder and markdowns.

Shall I create another task to look at these to exclude samples for generated markdowns after closing this one?

2023-04-21 15:58 UTC, JamJarchitect commented on infra-as-code/bicep/orchestration/hubPeeredSpoke/bicepconfig.json
> -          "level": "error"
Added back

2023-04-21 16:44 UTC, jtracey93 commented on infra-as-code/bicep/modules/privateDnsZoneLinks/samples/generateddocs/baseline.sample.bicep.md
my apologies, ignore this then

2023-04-21 17:22 UTC, JamJarchitect commented
/azp run validateazcloud

2023-04-21 18:06 UTC, closed without merging