Accelerator Documentation
Azure/ALZ-Bicep pull request #497
Opened 2023-04-20 03:32 UTC by oZakari

# Overview/Summary
GitHub Issue: #492
ADO: AB#17187

Adds initial documentation for the ALZ Bicep Accelerator and updates consumer guide to include the Accelerator as an implementation option.

## This PR fixes/adds/changes/removes

1. Adds initial documentation for the ALZ Bicep Accelerator
2. Updates consumer guide to include the Accelerator as an implementation option.

### Breaking Changes

None, only updating documentation.

## Testing Evidence

Not applicable as only related to documentation.

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [x] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [x] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [x] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

2023-04-20 16:07 UTC, oZakari commented on accelerator/README.md
> Do you think we should have this all in the wiki, and just have the README page link to it in the wiki?

Sure, I don't have a problem with that.

2023-04-21 05:10 UTC, oZakari commented
The lint error is because the file I am referencing is the README for the accelerator.

2023-04-21 14:29 UTC, jtracey93 requested changes

2023-04-21 14:29 UTC, jtracey93 commented on docs/wiki/Accelerator.md
This is looking great. Think it could do with a diagram or a `tree` output of the repo directory as an example for people to be able to relate a visual too

2023-04-21 18:36 UTC, oZakari commented on accelerator/README.md
> +This repo contains the Azure Landing Zones Bicep Accelerator. For additional information on the Accelerator, please refer to the [Wiki](https://github.com/Azure/ALZ-Bicep/blob/main/docs/wiki/Accelera
Done

2023-04-21 19:02 UTC, oZakari commented
Added last minute adjustment to remove hard-coded values. Good spot @stalejohnsen and thanks!

2023-04-22 06:54 UTC, jtracey93 requested changes

2023-04-22 06:54 UTC, jtracey93 commented on docs/wiki/ConsumerGuide.md
> +- Utilize the [ALZ Bicep Accelerator and associated documentation](https://github.com/Azure/ALZ-Bicep/accelerator/README.md)
```suggestion
- Utilize the [ALZ Bicep Accelerator and associated documentation](https://github.com/Azure/ALZ-Bicep/wiki/Accelerator)
```

2023-04-24 05:42 UTC, jtracey93 commented
/azp run validateazcloud

2023-04-24 07:55 UTC, merged