Add if (parAzBastionEnabled) to nsg create bastion
Azure/ALZ-Bicep pull request #575
Opened 2023-07-14 13:52 UTC by woutermation

Fixes #573

# Overview/Summary

When setting Bastion to disabled the NSG is still deployed, expect that the NSG is not deployed

By adding if (parAzBastionEnabled) to the NSG creation this is fixed

## This PR fixes/adds/changes/removes

Change hubNetworking.bicep line 368 with

```bicep
resource resBastionNsg 'Microsoft.Network/networkSecurityGroups@2021-08-01' = if (parAzBastionEnabled) {
}
```

### Breaking Changes

None

## Testing Evidence

NSG is not created ;-)

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [x] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [x] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

2023-07-14 14:05 UTC, jtracey93 requested changes
Hey @woutermation,

Thanks for the PR, much appreciated.

I think one more thing needs changing on line 287 to ensure that if Bastion isn't enabled the NSG isn't tried to be referenced: 

https://github.com/woutermation/ALZ-Bicep/blob/woutermation/issue573/infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep#L287-L291

Can you add to the condition that already exists to also check for `parAzBastionEnabled` being `true`?

Thanks

2023-07-15 06:17 UTC, woutermation commented
Good catch, I removed de AzureBastionSubnet from my parameter file that's why it didn't show up during testing (my bad ;-)) and note to self to always test with the default param file.

2023-07-17 07:42 UTC, jtracey93 approved these changes

2023-07-17 07:43 UTC, jtracey93 commented
/azp run validateazcloud

2023-07-17 08:08 UTC, merged