Add Bastion native client support
Azure/ALZ-Bicep pull request #607
Opened 2023-08-10 20:24 UTC by juang903

# Overview/Summary

Adds the option to enable Bastion native client support. Defaults to disabled.

2023-08-11 08:18 UTC, jtracey93 requested changes
Thanks @juang903 for the PR, please see the PR comments and also can you manually generate the doc updates by following this please https://github.com/Azure/ALZ-Bicep/wiki/Contributing#manually-generating-the-parameter-markdown-files

Thanks 

Jack

2023-08-11 08:18 UTC, jtracey93 commented on infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
> +param parBastionTunneling bool = false
```suggestion
param parAzBastionTunneling bool = false
```
making it match the others

2023-08-11 08:18 UTC, jtracey93 commented on infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
> +    enableTunneling: parBastionTunneling
```suggestion
    enableTunneling: (parAzBastionSku == 'Standard' && parAzBastionTunneling) ? parAzBastionTunneling : false
```

adding some logic for ensuring standard has been selected 👍

Can you please test both deploy with standard and basic to ensure all works

2023-08-11 08:18 UTC, jtracey93 commented on infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
> +@sys.description('Switch to enable/disable Bastion native client support.')
```suggestion
@sys.description('Switch to enable/disable Bastion native client support. This is only supported when the Standard SKU is used for Bastion as documented here: https://learn.microsoft.com/azure/bastion/native-client')
```

2023-08-11 18:12 UTC, juang903 commented
@microsoft-github-policy-service agree

2023-08-11 18:17 UTC, juang903 commented
Hey @jtracey93, updated with changes requested and markdown files.

2023-08-14 10:15 UTC, jtracey93 approved these changes
LGTM

2023-08-14 13:47 UTC, jtracey93 commented
/azp run validateazcloud

2023-08-14 14:19 UTC, merged