Add installation of ALZ Powershell module for policy scripts
Azure/ALZ-Bicep pull request #679
Opened 2023-11-10 06:11 UTC by oZakari

# Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## Testing Evidence

Replace this with any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [ ] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [ ] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

2023-11-10 14:56 UTC, jtracey93 commented
@ozakari these scripts are invoked by https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/update-policy.yml & https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/update-policy-china.yml, do we need to install the ALZ module as part of these workflows? Or is that already covered?

2023-11-13 21:54 UTC, oZakari commented
Thanks @jtracey93 for linking those, I've updated the MC workflow and added some logging as well.

2023-11-20 17:18 UTC, jtracey93 requested changes
couple of tweaks

2023-11-20 17:18 UTC, jtracey93 commented on .github/scripts/Invoke-PolicyToBicep-China.ps1
> +  Install-Module -Name ALZ -Scope CurrentUser -ErrorAction Stop
```suggestion
  Write-Information "====> ALZ module isn't already installed. Installing..." -InformationAction Continue
  Install-Module -Name ALZ -Force -Scope CurrentUser -ErrorAction Stop
  Write-Information "====> ALZ module now installed." -InformationAction Continue
```

2023-11-20 17:18 UTC, jtracey93 commented on .github/scripts/Invoke-PolicyToBicep.ps1
> +  Install-Module -Name ALZ -Scope CurrentUser -ErrorAction Stop
```suggestion
  Write-Information "====> ALZ module isn't already installed. Installing..." -InformationAction Continue
  Install-Module -Name ALZ -Force -Scope CurrentUser -ErrorAction Stop
  Write-Information "====> ALZ module now installed." -InformationAction Continue
```

2023-11-20 17:27 UTC, merged