Feat: Add Resource Locking to ALZ Bicep Modules
Azure/ALZ-Bicep pull request #712
Opened 2024-01-12 21:59 UTC by DaFitRobsta

# Overview/Summary

Adds the support for resource locking in all modules for resources that support resource locks. 
See #ADO30524 for additional details of feature request.
In response to #608 

## This PR fixes/adds/changes/removes

- Allows for setting resource locking globally or at each individual resource within the module.
- Resource locking at the subscription level is not supported in this release.

### Breaking Changes

None

## Testing Evidence

Each module that was updated to support Resource Locking was tested with successful deployments. Testing included setting the global parameter to different values as individual resources to validate resource locking logic.

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://github.com/Azure/ALZ-Bicep/wiki/Contributing) and ensured this PR is compliant with the guide
- [ ] Ensured the resource API versions in `.bicep` file/s I am adding/editing are using the latest API version possible
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/ALZ-Bicep/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/ALZ-Bicep/issues)
- [ ] *(ALZ Bicep Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/alz/bicep/backlog)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/ALZ-Bicep/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/ALZ-Bicep/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/ALZ-Bicep/tree/main/.github/workflows)
  - [E2E (End-To-End)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/bicep-build-to-validate.yml)
  - [ValidateAzCloud (Base validation in Azure Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/base-unit-validate.yml)
  - [ValidateMcCloud (Base validation in Azure China Cloud)](https://github.com/Azure/ALZ-Bicep/blob/main/tests/pipelines/mc-base-unit-validate.yml)
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)
- [ ] If relevant, created or updated Code Tours [here](https://github.com/Azure/ALZ-Bicep/blob/main/.vscode/tours)

2024-01-15 03:46 UTC, oZakari commented
Thanks @DaFitRobsta! Will go through this PR later this week. 👍🏼

2024-01-25 03:57 UTC, oZakari requested changes
Hey @DaFitRobsta, for the resource group module I see there is a new module called resourceGroupLock.bicep. Can we instead just use the resource lock provider as you have done for the other modules instead?

2024-01-25 04:22 UTC, oZakari requested changes

2024-01-25 04:22 UTC, oZakari commented on infra-as-code/bicep/modules/privateDnsZones/privateDnsZones.bicep
> +resource lock 'Microsoft.Authorization/locks@2020-05-01' = [for (privateDnsZone, index) in varPrivateDnsZonesMerge: if (parResourceLockConfig.kind != 'None') {
```suggestion
resource resPrivateDnsZonesLock 'Microsoft.Authorization/locks@2020-05-01' = [for (privateDnsZone, index) in varPrivateDnsZonesMerge: if (parResourceLockConfig.kind != 'None') {
```

2024-01-25 04:22 UTC, oZakari commented on infra-as-code/bicep/modules/privateDnsZones/privateDnsZones.bicep
> +resource lockLink 'Microsoft.Authorization/locks@2020-05-01' = [for (privateDnsZone, index) in varPrivateDnsZonesMerge: if (!empty(parVirtualNetworkIdToLink) && !empty(parResourceLockConfig ?? {}) &&
```suggestion
resource resVirtualNetworkLinkLock 'Microsoft.Authorization/locks@2020-05-01' = [for (privateDnsZone, index) in varPrivateDnsZonesMerge: if (!empty(parVirtualNetworkIdToLink) && !empty(parResourceLockConfig ?? {}) && parResourceLockConfig.kind != 'None') {
```

2024-01-25 04:22 UTC, oZakari commented on infra-as-code/bicep/modules/privateDnsZones/privateDnsZones.bicep
> +resource lockFailoverLink 'Microsoft.Authorization/locks@2020-05-01' = [for (privateDnsZone, index) in varPrivateDnsZonesMerge: if (!empty(parVirtualNetworkIdToLinkFailover) && !empty(parResourceLock
```suggestion
resource resVirtualNetworkLinkFailoverLock 'Microsoft.Authorization/locks@2020-05-01' = [for (privateDnsZone, index) in varPrivateDnsZonesMerge: if (!empty(parVirtualNetworkIdToLinkFailover) && !empty(parResourceLockConfig ?? {}) && parResourceLockConfig.kind != 'None') {
```

2024-01-25 04:22 UTC, oZakari commented on infra-as-code/bicep/modules/publicIp/publicIp.bicep
> +resource lock 'Microsoft.Authorization/locks@2020-05-01' = if (!empty(parResourceLockConfig ?? {}) && parResourceLockConfig.kind != 'None') {
```suggestion
resource resPublicIpLock 'Microsoft.Authorization/locks@2020-05-01' = if (!empty(parResourceLockConfig ?? {}) && parResourceLockConfig.kind != 'None') {
```

2024-01-25 04:22 UTC, oZakari commented on infra-as-code/bicep/modules/vwanConnectivity/parameters/vwanConnectivity.parameters.all.json
> +      "value": "westus3"
Please change this back to eastus.

2024-01-25 04:24 UTC, oZakari requested changes

2024-01-25 04:24 UTC, oZakari commented on infra-as-code/bicep/modules/spokeNetworking/parameters/spokeNetworking.parameters.all.json
> +      "value": "192.168.2.4"
Please revert.

2024-01-25 14:20 UTC, DaFitRobsta commented
> Hey @DaFitRobsta, for the resource group module I see there is a new module called resourceGroupLock.bicep. Can we instead just use the resource lock provider as you have done for the other modules instead?

Hey @oZakari,
Because the resource group module has a targetScope set to the subscription level, if placing the resource lock within the module, it locks the subscription and not the resource group. I used this site, https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources?tabs=bicep#template, as an example to work around the issue. It's my understanding that I have to call a sub-module in order to set the resource lock at the resource group level. If you have other methods to execute this without the extra module, please let me know.

2024-01-25 14:26 UTC, DaFitRobsta commented on infra-as-code/bicep/modules/spokeNetworking/parameters/spokeNetworking.parameters.all.json
> +      "value": "192.168.2.4"
You got it

2024-01-26 04:48 UTC, oZakari commented
> > Hey @DaFitRobsta, for the resource group module I see there is a new module called resourceGroupLock.bicep. Can we instead just use the resource lock provider as you have done for the other modules instead?
> 
> Hey @oZakari, Because the resource group module has a targetScope set to the subscription level, if placing the resource lock within the module, it locks the subscription and not the resource group. I used this site, https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources?tabs=bicep#template, as an example to work around the issue. It's my understanding that I have to call a sub-module in order to set the resource lock at the resource group level. If you have other methods to execute this without the extra module, please let me know.

Ah, that makes perfect sense. Thanks for the clarification on that!

2024-01-26 05:01 UTC, oZakari commented
/azp run validateazcloud

2024-01-26 05:59 UTC, oZakari commented
Hey @DaFitRobsta, the ValidateAzCloud pipeline failed due to parPublicIPLock not being declared within the hub networking module. Could you add that in when you get chance. After adding the fix, you can run put /azp run validateazcloud in a comment to re-trigger the pipeline.

2024-01-26 20:07 UTC, DaFitRobsta commented
/azp run validateazcloud

2024-01-29 01:21 UTC, oZakari approved these changes

2024-01-29 01:22 UTC, merged